[project]
name = "mysqlclusterbackup"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "configparser>=7.2.0",
    "inflect>=7.5.0",
]
